# Generated by Django 3.1.14 on 2024-11-08 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcserver', '0040_auto_20241108_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp_verified',
            field=models.BooleanField(default=True),
        ),
    ]
